language: python

python:
  - 3.5
osx_image: xcode7.3
env:
    - CC=clang   CXX=clang++

cache: pip

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-5
            - g++-5


before_install:
    - $CC --version
    - $CXX --version
    - python --version

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip
  - pip install -r requirements.txt
  - python setup.py install

# Run test
script:
  - py.test --cov=irtk irtk

# Calculate coverage
after_success:
  - coveralls
